export const environment = {
  firebase: {
    projectId: 'ng-gems',
    appId: '1:816887947706:web:31c25e00206df121437d83',
    databaseURL: 'https://ng-gems-default-rtdb.firebaseio.com',
    storageBucket: 'ng-gems.appspot.com',
    locationId: 'us-central',
    apiKey: 'AIzaSyD4Gv88PqciXAwBQO6S5Y04dH5McOdod0k',
    authDomain: 'ng-gems.firebaseapp.com',
    messagingSenderId: '816887947706',
    measurementId: 'G-RXNLSK1XZM',
  },
  production: true,
  gems_url: '${GEMS_URL}',
  chat_url: '${CHAT_URL}',
  locale_url: '${LOCALE_URL}',
  api_v3: '${GEMS_URL}/v1',
  kcsaccount_url: '${KCSACCOUNT_URL}',
  app_token: '${APP_TOKEN}',
  notification_period: 5000,
  newrelic_license_key: '${NEWRELIC_LICENSE_KEY}',
  newrelic_application_id: '${NEWRELIC_APPLICATION_ID}',
  intercom_app_id: '${INTERCOM_APP_ID}',
  gtm_id: '${GTM_ID}'
};
